# -*- coding: utf-8 -*-
"""AsentistaEdenAndrea_CS2_ActSet1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KwYGAMF_3-ow91jLcpaiQMAR9afPMFqf
"""

student = {}

name = input("Enter your name: ")
age = input("Enter your age: ")
subject = input("Enter your favorite subject: ")

student["name"] = name
student["age"] = age
student["subject"] = subject

print("\nStudent Record:")
print("Name:", student["name"])
print("Age:", student["age"])
print("Favorite Subject:", student["subject"])